.github: check PRs for introduced whitespace errors.
Add whitespace error check to our PR verification workflow/job.

Signed-off-by: Krisztian Litkey <krisztian.litkey@intel.com>

diff --git a/.github/workflows/project-checks.yaml b/.github/workflows/project-checks.yaml
--- a/.github/workflows/project-checks.yaml
+++ b/.github/workflows/project-checks.yaml
@@ -30,6 +30,15 @@ jobs:
         with:
           go-version: ${{ env.GO_VERSION }}
 
+      - name: Check PR for whitespace errors
+        if: ${{ github.event_name == 'pull_request' }}
+        run: |
+          if ! git diff-index --check origin/${{ github.base_ref }} --; then
+              echo "This PR would introduce the errors shown above."
+              echo "Please fix them and update the PR."
+              exit 1
+          fi
+
       - name: Verify dependencies
         run: |
           make verify-godeps
